### ISSUE TITLE
shaper play works only from the folder which consist playbook file

### ISSUE THREAD

**Issue by wenditer** [arno49/shaper#20]
e.g I have following folder structure:
```
root
  - workdir
    - playbooks
      - playbook_fe1.yml
    - templates
```

when I run shaper play workdir/playbooks/playbook_fe1.yml from directory root it shows me the following error:
```
Traceback (most recent call last):
  File "d:\Env\Python\Python37\Scripts\shaper-script.py", line 11, in <module>
    load_entry_point('shaper', 'console_scripts', 'shaper')()
  File "c:\env\pes-v2-atg\build\workdir\shaper\shaper-master\shaper\cli.py", line 133, in main
    rendered_templates.append(render_template(template, context))
  File "c:\env\pes-v2-atg\build\workdir\shaper\shaper-master\shaper\renderer.py", line 41, in render_template
    template = env.get_template(os.path.basename(template_path))
  File "d:\env\python\python37\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "d:\env\python\python37\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "d:\env\python\python37\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "d:\env\python\python37\lib\site-packages\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: FE.tmpl
```

**Comment by arno49** [comment]
Fixed in 0.1.1
