### ISSUE TITLE
shaper write throws an error TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by wenditer** [arno49/shaper#21]
I run followin command: shaper write shaper/playbooks/templates.yaml -o shaper/playbooks/files_fe1

result is an error:
```
Traceback (most recent call last):
  File "d:\Env\Python\Python37\Scripts\shaper-script.py", line 11, in <module>
    load_entry_point('shaper', 'console_scripts', 'shaper')()
  File "c:\env\pes-v2-atg\build\workdir\shaper\shaper-master\shaper\cli.py", line 161, in main
    manager.write_properties(datastructure, arguments.out)
  File "c:\env\pes-v2-atg\build\workdir\shaper\shaper-master\shaper\manager.py", line 51, in write_properties
    properties,
  File "c:\env\pes-v2-atg\build\workdir\shaper\shaper-master\shaper\lib\configi.py", line 427, in write
    return parser(path_to_file, data)
  File "c:\env\pes-v2-atg\build\workdir\shaper\shaper-master\shaper\lib\configi.py", line 324, in write_property
    ) for item in data.items()
  File "c:\env\pes-v2-atg\build\workdir\shaper\shaper-master\shaper\lib\configi.py", line 157, in write_plain_text
    _fd.write(content)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by arno49** [comment]
fixed in 0.0.6
